version: '3.3'

services:
  template-service:
    image: template-service
    container_name: template-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    volumes:
      - ./data/template-service:/microservice/data
    networks:
      - template

  template-db:
    image: postgres:alpine
    container_name: template-db
    restart: always
    environment:
      POSTGRES_USER: template
      POSTGRES_PASSWORD: template
      POSTGRES_DB: Template
    volumes:
      - ./data/template-service/postgres:/var/lib/postgresql/data
    networks:
    - template
    
networks:
  template: